name: change-tag-line
description: changes a line in a text file from "tag 1" to "tag 2"
inputs:
  file-path:
    description: path of the file that will be updated
    required: true
  old-tag:
    description: this tag will be replaced by the new-tag
    required: true
    default: "tag 1"
  new-tag:
    description: this tag replaces the old-tag 
    required: true
    default: "tag 2"
runs:
  using: "composite"
  steps:
    - name: change the line in the text file from "tag 1" to "tag 2"
      run: | 
        printf "File content: '${{ inputs.file-path }}'\n"
        touch output.txt
        cat ${{ inputs.file-path }} >> output.txt
        cat output.txt
        
        printf "\nReplacing '${{ inputs.old-tag }}' with '${{ inputs.new-tag }}'"
        sed -i "s/${{ inputs.old-tag }}/${{ inputs.new-tag }}/g" output.txt
        
        printf "\nUpdated file content: 'output.txt'\n"
        echo "output_file=output.txt" >> $GITHUB_OUTPUT
        cat output.txt
      shell: bash
